name: Prepare PR

on:
  pull_request:
    branches:
      - main


jobs:
  test_and_preview:
    name: Test and Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
